# Market Regime Hybrid 전략 전용 Config

# VIX 임계값
VIX_VOLATILE_THRESHOLD = 25
VIX_HIGH_RISK_THRESHOLD = 30
VIX_LOW_RISK_THRESHOLD = 15

# VIX 기반 점수 조정 배수
VIX_HIGH_RISK_MULTIPLIER = 0.7   # VIX > 30
VIX_LOW_RISK_MULTIPLIER = 1.2    # VIX < 15

# 장기추세 가중치
BULLISH_BONUS = 1.2
BEARISH_BONUS = 1.2 